apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      initContainers:
      - name: "volume-mount-permission"
        image: "busybox"
        command: ["/bin/chown", "-R", "1000", "/var/jenkins_home"]
        env:
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        volumeMounts:
          - name: "jenkins-home"
            mountPath: "/var/jenkins_home"
        securityContext:
          runAsUser: 0
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
          
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: agent
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - jenkins.yogiman.cn
    secretName: yogiman.cn
  rules:
  - host: jenkins.yogiman.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80
